### ISSUE TITLE
Could not pass event SignChangeEvent to AdvancedRegionMarket v2.1.5

### ISSUE THREAD

**Issue by derMiepz** [alex9849/advanced-region-market#10]
Heya. Not sure what caused that and if that's an actual problem as it didn't cause any issues and didn't give any errors in the chat, but I thought it could be useful for you:
```
[02:44:28 INFO]: derMiepz issued server command: /arm hotel list
[02:44:28 INFO]: /arm hotel list
[02:45:45 ERROR]: Could not pass event SignChangeEvent to AdvancedRegionMarket v2.1.5
java.lang.NullPointerException: null
	at net.alex9849.arm.regions.Region.getPrice(Region.java:428) ~[?:?]
	at net.alex9849.arm.regions.Region.lambda$new$3(Region.java:76) ~[?:?]
	at net.alex9849.arm.util.stringreplacer.StringReplacer.replace(StringReplacer.java:49) ~[?:?]
	at net.alex9849.arm.util.stringreplacer.StringReplacer.replace(StringReplacer.java:24) ~[?:?]
	at net.alex9849.arm.regions.Region.getConvertedMessage(Region.java:916) ~[?:?]
	at net.alex9849.arm.regions.CountdownRegion.getConvertedMessage(CountdownRegion.java:208) ~[?:?]
	at net.alex9849.arm.regions.RentRegion.getConvertedMessage(RentRegion.java:235) ~[?:?]
	at net.alex9849.arm.regions.RentRegion.updateSignText(RentRegion.java:109) ~[?:?]
	at net.alex9849.arm.regions.Region.updateSigns(Region.java:418) ~[?:?]
	at net.alex9849.arm.regions.CountdownRegion.setPrice(CountdownRegion.java:186) ~[?:?]
	at net.alex9849.arm.regions.RentRegion.setPrice(RentRegion.java:220) ~[?:?]
	at net.alex9849.arm.handler.listener.SignModifyListener.addSign(SignModifyListener.java:181) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor430.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-172]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-172]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-172]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-172]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2586) ~[patched_1.15.2.jar:git-Paper-172]
	at net.minecraft.server.v1_15_R1.PacketPlayInUpdateSign.a(SourceFile:44) ~[patched_1.15.2.jar:git-Paper-172]
	at net.minecraft.server.v1_15_R1.PacketPlayInUpdateSign.a(SourceFile:10) ~[patched_1.15.2.jar:git-Paper-172]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-172]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-172]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-172]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-172]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-172]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1058) ~[patched_1.15.2.jar:git-Paper-172]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1051) ~[patched_1.15.2.jar:git-Paper-172]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-172]
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1021) ~[patched_1.15.2.jar:git-Paper-172]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:944) ~[patched_1.15.2.jar:git-Paper-172]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
```

**Comment by alex9849** [comment]
Have you changed the price for one of your regions? If yes how?

**Comment by alex9849** [comment]
How how have you created the region

**Comment by derMiepz** [comment]
I didn't change the price. I set it directly to 200 via `/arm sellpreset price 200`, created a preset and created signs with an empty last line.

**Comment by alex9849** [comment]
ok. Is it better with the current version?
