### ISSUE TITLE
Task #76 for AdvancedRegionMarket v3.3.7 generated an exception

### ISSUE THREAD

**Issue by CombatMedic02** [alex9849/advanced-region-market#104]
After updating to Minecraft 1.18.2 I get this error continually posting in my console:

[01:50:24] [Server thread/WARN]: [AdvancedRegionMarket] Task #76 for AdvancedRegionMarket v3.3.7 generated an exception
java.lang.RuntimeException: com.sk89q.worldedit.bukkit.adapter.UnsupportedVersionEditException: Editing on unsupported versions is disabled.
	at com.sk89q.worldedit.bukkit.BukkitWorld.getBlock(BukkitWorld.java:457) ~[worldedit-bukkit-7.2.9.jar:?]
	at com.sk89q.worldedit.bukkit.BukkitWorld.getFullBlock(BukkitWorld.java:491) ~[worldedit-bukkit-7.2.9.jar:?]
	at com.sk89q.worldedit.EditSession.getFullBlock(EditSession.java:686) ~[worldedit-bukkit-7.2.9.jar:?]
	at com.sk89q.worldedit.function.block.ExtentBlockCopy.apply(ExtentBlockCopy.java:72) ~[worldedit-bukkit-7.2.9.jar:?]
	at com.sk89q.worldedit.function.RegionMaskingFilter.apply(RegionMaskingFilter.java:53) ~[worldedit-bukkit-7.2.9.jar:?]
	at com.sk89q.worldedit.function.visitor.RegionVisitor.resume(RegionVisitor.java:60) ~[worldedit-bukkit-7.2.9.jar:?]
	at com.sk89q.worldedit.function.operation.OperationQueue.resume(OperationQueue.java:92) ~[worldedit-bukkit-7.2.9.jar:?]
	at com.sk89q.worldedit.function.operation.DelegateOperation.resume(DelegateOperation.java:52) ~[worldedit-bukkit-7.2.9.jar:?]
	at com.sk89q.worldedit.function.operation.Operations.completeLegacy(Operations.java:55) ~[worldedit-bukkit-7.2.9.jar:?]
	at net.alex9849.adapters.WorldEdit7.createSchematic(WorldEdit7.java:59) ~[advancedregionmarket-3.3.7.jar:?]
	at net.alex9849.arm.regions.Region.createBackup(Region.java:912) ~[advancedregionmarket-3.3.7.jar:?]
	at net.alex9849.arm.regions.Region.unsell(Region.java:1106) ~[advancedregionmarket-3.3.7.jar:?]
	at net.alex9849.arm.regions.CountdownRegion.unsell(CountdownRegion.java:67) ~[advancedregionmarket-3.3.7.jar:?]
	at net.alex9849.arm.regions.Region.automaticResetRegion(Region.java:1075) ~[advancedregionmarket-3.3.7.jar:?]
	at net.alex9849.arm.regions.RentRegion.updateRegion(RentRegion.java:148) ~[advancedregionmarket-3.3.7.jar:?]
	at net.alex9849.arm.regions.RegionManager$UpdateScheduler.updateNextGroup(RegionManager.java:972) ~[advancedregionmarket-3.3.7.jar:?]
	at net.alex9849.arm.regions.RegionManager.doTick(RegionManager.java:876) ~[advancedregionmarket-3.3.7.jar:?]
	at net.alex9849.arm.AdvancedRegionMarket.lambda$startup$0(AdvancedRegionMarket.java:223) ~[advancedregionmarket-3.3.7.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-290]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.2.jar:git-Paper-290]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1531) ~[paper-1.18.2.jar:git-Paper-290]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-290]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1455) ~[paper-1.18.2.jar:git-Paper-290]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225) ~[paper-1.18.2.jar:git-Paper-290]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-290]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: com.sk89q.worldedit.bukkit.adapter.UnsupportedVersionEditException: Editing on unsupported versions is disabled.
	... 26 more

Is this a bug or can I do something to fix this on my end?

**Comment by CombatMedic02** [comment]
It seems that updating worldedit has fixed this message.
