### ISSUE TITLE
Could not pass event InventoryClickEvent to AdvancedRegionMarket v3.0.1

### ISSUE THREAD

**Issue by DerSebiii** [alex9849/advanced-region-market#11]
When I use /arm gui and I like to open the "My Region (Owner)" inventory, this error is displayed in the console.

`[18.04.2020 11:30:06] INFO: [Adventuria-1] [11:30:05 ERROR]: Could not pass event InventoryClickEvent to AdvancedRegionMarket v3.0.1

[18.04.2020 11:30:06] INFO: [Adventuria-1] java.lang.NullPointerException: null

[18.04.2020 11:30:06] INFO: [Adventuria-1]      at java.util.ArrayList.<init>(ArrayList.java:178) ~[?:1.8.0_242]

[18.04.2020 11:30:06] INFO: [Adventuria-1]      at net.alex9849.arm.gui.Gui.getRegionDisplayItem(Gui.java:1381) ~[?:?]

[18.04.2020 11:30:06] INFO: [Adventuria-1]      at net.alex9849.arm.gui.Gui.openRegionOwnerGui(Gui.java:143) ~[?:?]

[18.04.2020 11:30:06] INFO: [Adventuria-1]      at net.alex9849.arm.gui.Gui$1.execute(Gui.java:93) ~[?:?]

[18.04.2020 11:30:06] INFO: [Adventuria-1]      at net.alex9849.arm.gui.Gui.onClick(Gui.java:1884) ~[?:?]

[18.04.2020 11:30:06] INFO: [Adventuria-1]      at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor444.execute(Unknown Source) ~[?:?]

[18.04.2020 11:30:06] INFO: [Adventuria-1]      at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.13.2.jar:git-Paper-651]

[18.04.2020 11:30:06] INFO: [Adventuria-1]      at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-651]

[18.04.2020 11:30:06] INFO: [Adventuria-1]      at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-651]

[18.04.2020 11:30:06] INFO: [Adventuria-1]      at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-651]

[18.04.2020 11:30:06] INFO: [Adventuria-1]      at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2288) ~[patched_1.13.2.jar:git-Paper-651]

[18.04.2020 11:30:06] INFO: [Adventuria-1]      at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.13.2.jar:git-Paper-651]

[18.04.2020 11:30:06] INFO: [Adventuria-1]      at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.13.2.jar:git-Paper-651]

[18.04.2020 11:30:06] INFO: [Adventuria-1]     
 at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-651]

[18.04.2020 11:30:06] INFO: [Adventuria-1]      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_242]

[18.04.2020 11:30:06] INFO: [Adventuria-1]      at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_242]

[18.04.2020 11:30:06] INFO: [Adventuria-1]      at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-651]

[18.04.2020 11:30:06] INFO: [Adventuria-1]      at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.2.jar:git-Paper-651]

[18.04.2020 11:30:06] INFO: [Adventuria-1]      at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-651]

[18.04.2020 11:30:06] INFO: [Adventuria-1]      at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-651]

[18.04.2020 11:30:06] INFO: [Adventuria-1]      at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-651]

[18.04.2020 11:30:06] INFO: [Adventuria-1]      at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
`

**Comment by alex9849** [comment]
Thanks for your bugreport! :)
I've just uploaded a new version (3.0.2), that fixed that bug.
