### ISSUE TITLE
1.19 Error

### ISSUE THREAD

**Issue by meowsome** [alex9849/advanced-region-market#110]
Hi,

I'm running 1.19 Paper build 14, and I'm experiencing an error when trying to sell a rented region. I believe it's something to do with resetting the region to how it was before, and also editing the text on the sign. When I try to sell a rented region, the region is not reset and the rent sign doesn't change. 

Here's the error in console when trying to sell a rented region:

```
[18:51:57 ERROR]: Could not pass event InventoryClickEvent to AdvancedRegionMarket v3.3.7
java.lang.ExceptionInInitializerError: null
        at com.sk89q.worldedit.EditSession.<init>(EditSession.java:269) ~[worldedit-bukkit-7.2.8.jar:?]
        at com.sk89q.worldedit.EditSessionBuilder.build(EditSessionBuilder.java:143) ~[worldedit-bukkit-7.2.8.jar:?]
        at com.sk89q.worldedit.EditSessionFactory$EditSessionFactoryImpl.getEditSession(EditSessionFactory.java:172) ~[worldedit-bukkit-7.2.8.jar:?]
        at com.sk89q.worldedit.EditSessionFactory$EditSessionFactoryImpl.getEditSession(EditSessionFactory.java:152) ~[worldedit-bukkit-7.2.8.jar:?]
        at net.alex9849.adapters.WorldEdit7.createSchematic(WorldEdit7.java:52) ~[advancedregionmarket-3.3.7.jar:?]
        at net.alex9849.arm.regions.Region.createBackup(Region.java:912) ~[advancedregionmarket-3.3.7.jar:?]
        at net.alex9849.arm.regions.Region.unsell(Region.java:1106) ~[advancedregionmarket-3.3.7.jar:?]
        at net.alex9849.arm.regions.CountdownRegion.unsell(CountdownRegion.java:67) ~[advancedregionmarket-3.3.7.jar:?]
        at net.alex9849.arm.regions.Region.automaticResetRegion(Region.java:1075) ~[advancedregionmarket-3.3.7.jar:?]
        at net.alex9849.arm.regions.Region.userSell(Region.java:1054) ~[advancedregionmarket-3.3.7.jar:?]
        at net.alex9849.arm.gui.Gui.lambda$openSellWarning$63(Gui.java:783) ~[advancedregionmarket-3.3.7.jar:?]
        at net.alex9849.arm.gui.Gui.onClick(Gui.java:981) ~[advancedregionmarket-3.3.7.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor457.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:git-Paper-14]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:664) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3047) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.jar:git-Paper-14]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1358) ~[paper-1.19.jar:git-Paper-14]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183) ~[paper-1.19.jar:git-Paper-14]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1335) ~[paper-1.19.jar:git-Paper-14]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1328) ~[paper-1.19.jar:git-Paper-14]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1306) ~[paper-1.19.jar:git-Paper-14]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[paper-1.19.jar:git-Paper-14]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-14]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:889) ~[guava-31.0.1-jre.jar:?]
        at com.sk89q.worldedit.bukkit.BukkitBlockCategoryRegistry.getCategorisedByName(BukkitBlockCategoryRegistry.java:47) ~[worldedit-bukkit-7.2.8.jar:?]
        at com.sk89q.worldedit.world.registry.CategoryRegistry.getAll(CategoryRegistry.java:41) ~[worldedit-bukkit-7.2.8.jar:?]
        at com.sk89q.worldedit.world.block.BlockCategory.load(BlockCategory.java:46) ~[worldedit-bukkit-7.2.8.jar:?]
        at com.sk89q.worldedit.registry.Category.getAll(Category.java:40) ~[worldedit-bukkit-7.2.8.jar:?]
        at com.sk89q.worldedit.extent.reorder.MultiStageReorder.<clinit>(MultiStageReorder.java:63) ~[worldedit-bukkit-7.2.8.jar:?]
        ... 34 more
```

Here's the error in console when trying to create a new shop using the signlinkmode method

```
[18:55:51] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to AdvancedRegionMarket v3.3.7
java.lang.NoClassDefFoundError: Could not initialize class com.sk89q.worldedit.extent.reorder.MultiStageReorder
	at com.sk89q.worldedit.EditSession.<init>(EditSession.java:269) ~[worldedit-bukkit-7.2.8.jar:?]
	at com.sk89q.worldedit.EditSessionBuilder.build(EditSessionBuilder.java:143) ~[worldedit-bukkit-7.2.8.jar:?]
	at com.sk89q.worldedit.EditSessionFactory$EditSessionFactoryImpl.getEditSession(EditSessionFactory.java:172) ~[worldedit-bukkit-7.2.8.jar:?]
	at com.sk89q.worldedit.EditSessionFactory$EditSessionFactoryImpl.getEditSession(EditSessionFactory.java:152) ~[worldedit-bukkit-7.2.8.jar:?]
	at net.alex9849.adapters.WorldEdit7.createSchematic(WorldEdit7.java:52) ~[advancedregionmarket-3.3.7.jar:?]
	at net.alex9849.arm.regions.Region.createSchematic(Region.java:921) ~[advancedregionmarket-3.3.7.jar:?]
	at net.alex9849.arm.minifeatures.SignLinkMode.registerRegion(SignLinkMode.java:170) ~[advancedregionmarket-3.3.7.jar:?]
	at net.alex9849.arm.minifeatures.SignLinkMode.playerClick(SignLinkMode.java:135) ~[advancedregionmarket-3.3.7.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:git-Paper-14]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:664) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:544) ~[paper-1.19.jar:git-Paper-14]
	at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:527) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1872) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.jar:git-Paper-14]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1358) ~[paper-1.19.jar:git-Paper-14]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183) ~[paper-1.19.jar:git-Paper-14]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1335) ~[paper-1.19.jar:git-Paper-14]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1328) ~[paper-1.19.jar:git-Paper-14]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1306) ~[paper-1.19.jar:git-Paper-14]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[paper-1.19.jar:git-Paper-14]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-14]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

Hopefully these help. Thanks.

**Comment by alex9849** [comment]
These are all errors that are caused by worldedit. Try up update to the newest worldedit version. :)

**Comment by meowsome** [comment]
Thanks, my apologies, I should have read the errors more in depth
