### ISSUE TITLE
Could not pass sign change event.

### ISSUE THREAD

**Issue by RustyDagger** [alex9849/advanced-region-market#3]
Iv ran into this issue popping up in console when I try to create a sign with my shop preset.
Im sure this is just some dumb config error on my part. 

**The console Error:**

`>....       [16:54:56]: RustyDagger issued server command: /arm rentpreset load shop
>....       [16:55:11 ERROR: Could not pass event SignChangeEvent to AdvancedRegionMarket v2.1.5]
java.lang.NullPointerException: null
    at net.alex9849.arm.regions.Region.getPrice(Region.java:428) ~[?:?]
    at net.alex9849.arm.regions.Region.lambda$new$3(Region.java:76) ~[?:?]
    at net.alex9849.arm.util.stringreplacer.StringReplacer.replace(StringReplacer.java:49) ~[?:?]
    at net.alex9849.arm.util.stringreplacer.StringReplacer.replace(StringReplacer.java:24) ~[?:?]
    at net.alex9849.arm.regions.Region.getConvertedMessage(Region.java:916) ~[?:?]
    at net.alex9849.arm.regions.CountdownRegion.getConvertedMessage(CountdownRegion.java:208) ~[?:?]
    at net.alex9849.arm.regions.RentRegion.getConvertedMessage(RentRegion.java:235) ~[?:?]
    at net.alex9849.arm.regions.RentRegion.updateSignText(RentRegion.java:109) ~[?:?]
    at net.alex9849.arm.regions.Region.updateSigns(Region.java:418) ~[?:?]
    at net.alex9849.arm.regions.CountdownRegion.setPrice(CountdownRegion.java:186) ~[?:?]
    at net.alex9849.arm.regions.RentRegion.setPrice(RentRegion.java:220) ~[?:?]
    at net.alex9849.arm.handler.listener.SignModifyListener.addSign(SignModifyListener.java:181) ~[?:?]
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor662.execute(Unknown Source) ~[?:?]
    at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-146]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-146]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-146]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-146]
    at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2586) ~[patched_1.15.2.jar:git-Paper-146]
    at net.minecraft.server.v1_15_R1.PacketPlayInUpdateSign.a(SourceFile:44) ~[patched_1.15.2.jar:git-Paper-146]
    at net.minecraft.server.v1_15_R1.PacketPlayInUpdateSign.a(SourceFile:10) ~[patched_1.15.2.jar:git-Paper-146]
    at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-146]
    at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-146]
    at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-146]
    at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-146]
    at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-146]
    at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[patched_1.15.2.jar:git-Paper-146]
    at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[patched_1.15.2.jar:git-Paper-146]
    at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.15.2.jar:git-Paper-146]
    at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1172) ~[patched_1.15.2.jar:git-Paper-146]
    at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-146]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]`

My files.

[my files.zip](https://github.com/alex9849/advanced-region-market/files/4419131/my.files.zip)

**Comment by alex9849** [comment]
Ok. That looks like a bug in the preset system. But anyway the preset system gets completely rewritten in the next version, but I will especially take care for that bug.

**Comment by alex9849** [comment]
Bug should be fixed with the newest version.
