### ISSUE TITLE
ARM Throwing Errors 1.16.2 and disabling

### ISSUE THREAD

**Issue by banit** [alex9849/advanced-region-market#40]
11:42:54
Error occurred while enabling AdvancedRegionMarket v3.2.4 (Is it up to date?)
Console 11:42:54
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Double
at net.alex9849.arm.presets.PresetPatternManager.generatePresetObject(PresetPatternManager.java:31) ~[?:?]
at net.alex9849.arm.presets.PresetPatternManager.loadSavedObjects(PresetPatternManager.java:100) ~[?:?]
at net.alex9849.arm.util.YamlFileManager.<init>(YamlFileManager.java:24) ~[?:?]
at net.alex9849.arm.presets.PresetPatternManager.<init>(PresetPatternManager.java:20) ~[?:?]
at net.alex9849.arm.AdvancedRegionMarket.onEnable(AdvancedRegionMarket.java:201) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.2.jar:git-Paper-160]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.2.jar:git-Paper-160]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.2.jar:git-Paper-160]
at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:499) ~[patched_1.16.2.jar:git-Paper-160]
at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:413) ~[patched_1.16.2.jar:git-Paper-160]
at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.2.jar:git-Paper-160]
at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.2.jar:git-Paper-160]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.2.jar:git-Paper-160]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-160]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
INFO 11:42:54
[AdvancedRegionMarket]: Disabling AdvancedRegionMarket v3.2.4
ERROR 11:42:54
Error occurred while disabling AdvancedRegionMarket v3.2.4 (Is it up to date?)
Console 11:42:54
java.lang.NullPointerException: null
at net.alex9849.arm.AdvancedRegionMarket.onDisable(AdvancedRegionMarket.java:269) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.2.jar:git-Paper-160]
at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.16.2.jar:git-Paper-160]
at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.16.2.jar:git-Paper-160]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:384) ~[patched_1.16.2.jar:git-Paper-160]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.2.jar:git-Paper-160]
at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:499) ~[patched_1.16.2.jar:git-Paper-160]
at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:413) ~[patched_1.16.2.jar:git-Paper-160]
at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.2.jar:git-Paper-160]
at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.2.jar:git-Paper-160]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.2.jar:git-Paper-160]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-160]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]

**Comment by alex9849** [comment]
Ohh ok I see the problem. One question: Have you edited the preset config file manually?

**Comment by banit** [comment]
Yes, with notepad++ so the yaml code stays correct.

**Comment by alex9849** [comment]
Ok that error gets thrown because you propably have a integer number somewhere where you should have a point number in your presets.yml. Make shure that prices even if they are an integer value are represented by a point number

**Comment by banit** [comment]
rentpreset:
  shopklein:
    autorestore: true
    userrestorable: true
    hasExtendTime: false
    extendTime: 0
    inactivityReset: true
    flaggroup: Default
    entityLimitGroup: Default
    hasMaxRentTime: true
    maxRentTime: 28d
    hasExtendPerClick: true
    price: 2500
    hasPrice: true
    isUserResettable: true
    allowedSubregions: 0
    regionKind: shop
    isHotel: false
    doBlockReset: true
    extendPerClick: 7d
    autoreset: true
    setupcommands: []
  shopgross:
    autorestore: true
    userrestorable: true
    hasExtendTime: false
    extendTime: 0
    inactivityReset: true
    flaggroup: Default
    entityLimitGroup: Default
    hasMaxRentTime: true
    maxRentTime: 28d
    hasExtendPerClick: true
    price: 5000
    hasPrice: true
    isUserResettable: true
    allowedSubregions: 0
    regionKind: shop
    isHotel: false
    doBlockReset: true
    extendPerClick: 7d
    autoreset: true
    setupcommands: []
sellpreset:
  50x50:
    autorestore: true
    userrestorable: true
    inactivityReset: true
    flaggroup: Default
    price: 0
    hasPrice: false
    isUserResettable: true
    allowedSubregions: 0
    regionKind: starter
    isHotel: false
    doBlockReset: true
    entityLimitGroup: starter
    autoreset: true
    setupcommands: []
contractpreset: {}


I dont see the issue to be honest

**Comment by alex9849** [comment]
Everytime you wrote a price you should've used a comma number. For example 5000.0 instead of 5000
