### ISSUE TITLE
Plugin fails to enable on Paper #418 1.16.5

### ISSUE THREAD

**Issue by cobrex1** [alex9849/advanced-region-market#56]
Updated paper and ARM failed to load:

[11:01:03] [Server thread/INFO]: [AdvancedRegionMarket] Enabling AdvancedRegionMarket v${project.version}
[11:01:03] [Server thread/INFO]: [AdvancedRegionMarket] Using WorldGuard7 adapter
[11:01:03] [Server thread/INFO]: [AdvancedRegionMarket] Using WorldEdit7 adapter
[11:01:03] [Server thread/INFO]: [AdvancedRegionMarket] Using MC 1.14 sign adapter
[11:01:03] [Server thread/ERROR]: Error occurred while enabling AdvancedRegionMarket v${project.version} (Is it up to date?)
java.lang.NumberFormatException: For input string: "${project"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_211]
	at java.lang.Integer.parseInt(Integer.java:569) ~[?:1.8.0_211]
	at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_211]
	at java.util.stream.ReferencePipeline$4$1.accept(ReferencePipeline.java:210) ~[?:1.8.0_211]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:1.8.0_211]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_211]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_211]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:545) ~[?:1.8.0_211]
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:1.8.0_211]
	at java.util.stream.IntPipeline.toArray(IntPipeline.java:502) ~[?:1.8.0_211]
	at net.alex9849.arm.Updater.updateConfigs(Updater.java:21) ~[?:?]
	at net.alex9849.arm.AdvancedRegionMarket.startup(AdvancedRegionMarket.java:149) ~[?:?]
	at net.alex9849.arm.AdvancedRegionMarket.onEnable(AdvancedRegionMarket.java:121) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-418]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Paper-418]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-418]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Paper-418]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-418]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:464) ~[patched_1.16.5.jar:git-Paper-418]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.5.jar:git-Paper-418]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:935) ~[patched_1.16.5.jar:git-Paper-418]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.5.jar:git-Paper-418]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
[11:01:03] [Server thread/INFO]: [AdvancedRegionMarket] Disabling AdvancedRegionMarket v${project.version}
[11:01:03] [Server thread/ERROR]: Error occurred while disabling AdvancedRegionMarket v${project.version} (Is it up to date?)
java.lang.NullPointerException: null
	at net.alex9849.arm.AdvancedRegionMarket.onDisable(AdvancedRegionMarket.java:289) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.5.jar:git-Paper-418]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.16.5.jar:git-Paper-418]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.16.5.jar:git-Paper-418]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:384) ~[patched_1.16.5.jar:git-Paper-418]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-418]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Paper-418]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-418]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:464) ~[patched_1.16.5.jar:git-Paper-418]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.5.jar:git-Paper-418]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:935) ~[patched_1.16.5.jar:git-Paper-418]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.5.jar:git-Paper-418]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]

Thanks for looking into this when you get a moment.

**Comment by alex9849** [comment]
There was one release that had some environmental-variables that didn't got replaced during the building process. That release was published on spigot and was online for around 3 hours. This release has been replaced with a working version and got deleted. It looks like you have been unlucky and downloaded the version with the not replaced placeholders. You should be able to fix it by downloading the plugin again and deleting your config.yml
