### ISSUE TITLE
Could not pass event RestoreRegionEvent to ArmShopBridge v1.2.5

### ISSUE THREAD

**Issue by ArtamaMeyer** [alex9849/advanced-region-market#72]
When unrenting an area using quickshop 4.0.0.7
ARM 3.3.4
Bridge 1.2.5

```
[14:07:07 ERROR]: Could not pass event RestoreRegionEvent to ArmShopBridge v1.2.5
java.lang.NoSuchMethodError: 'java.util.Map org.maxgamer.quickshop.api.ShopAPI.getShop(org.bukkit.Chunk)'
        at net.alex9849.armshopbridge.adapters.QuickShop4Adapter.deleteShops(QuickShop4Adapter.java:35) ~[?:?]
        at net.alex9849.armshopbridge.listener.RestoreRegionListener.handleRegionReset(RestoreRegionListener.java:17) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor388.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-782]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-782]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-782]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-782]
        at net.alex9849.arm.regions.Region.restoreRegion(Region.java:936) ~[?:?]
        at net.alex9849.arm.regions.Region.automaticResetRegion(Region.java:1081) ~[?:?]
        at net.alex9849.arm.regions.Region.userSell(Region.java:1055) ~[?:?]
        at net.alex9849.arm.gui.Gui.lambda$openSellWarning$63(Gui.java:781) ~[?:?]
        at net.alex9849.arm.gui.Gui.onClick(Gui.java:974) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor330.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-782]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-782]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-782]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-782]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2715) ~[patched_1.16.5.jar:git-Paper-782]
        at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.5.jar:git-Paper-782]
        at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.5.jar:git-Paper-782]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-782]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-782]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-782]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-782]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-782]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1266) ~[patched_1.16.5.jar:git-Paper-782]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1259) ~[patched_1.16.5.jar:git-Paper-782]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-782]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1220) ~[patched_1.16.5.jar:git-Paper-782]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1134) ~[patched_1.16.5.jar:git-Paper-782]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-782]
        at java.lang.Thread.run(Thread.java:834) [?:?]
[14:07:08 INFO]: [AdvancedRegionMarket] Region c1 has been restored! Reason: USER_SELL
[14:07:09 INFO]: [WorldGuard] Region data changes made in 'world' have been background saved
```

**Comment by ArtamaMeyer** [comment]
Already reported https://github.com/alex9849/arm-shopbridge/issues/8
