### ISSUE TITLE
Bug/Error Message each time Shop Expires

### ISSUE THREAD

**Issue by TreemanKing** [alex9849/advanced-region-market#87]
```[13:35:44] [Server thread/INFO]: [AdvancedRegionMarket] Region shop028 has been unsold! Reason: EXPIRED
[13:35:44] [Server thread/ERROR]: Could not pass event RestoreRegionEvent to ArmShopBridge v1.2.5
java.lang.IncompatibleClassChangeError: Method 'org.maxgamer.quickshop.api.ShopAPI org.maxgamer.quickshop.api.QuickShopAPI.getShopAPI()' must be InterfaceMethodref constant
	at net.alex9849.armshopbridge.adapters.QuickShop4Adapter.deleteShops(QuickShop4Adapter.java:35) ~[armshopbridge.jar:?]
	at net.alex9849.armshopbridge.listener.RestoreRegionListener.handleRegionReset(RestoreRegionListener.java:17) ~[armshopbridge.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor803.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-104]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at net.alex9849.arm.regions.Region.restoreRegion(Region.java:936) ~[advancedregionmarket-3.3.6.jar:?]
	at net.alex9849.arm.regions.Region.automaticResetRegion(Region.java:1081) ~[advancedregionmarket-3.3.6.jar:?]
	at net.alex9849.arm.regions.RentRegion.updateRegion(RentRegion.java:170) ~[advancedregionmarket-3.3.6.jar:?]
	at net.alex9849.arm.regions.RegionManager$UpdateScheduler.updateNextGroup(RegionManager.java:972) ~[advancedregionmarket-3.3.6.jar:?]
	at net.alex9849.arm.regions.RegionManager.doTick(RegionManager.java:876) ~[advancedregionmarket-3.3.6.jar:?]
	at net.alex9849.arm.AdvancedRegionMarket.lambda$startup$0(AdvancedRegionMarket.java:223) ~[advancedregionmarket-3.3.6.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-104]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.1.jar:git-Paper-104]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1547) ~[paper-1.18.1.jar:git-Paper-104]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-104]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-104]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-104]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-104]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[13:35:45] [Server thread/INFO]: [AdvancedRegionMarket] Region shop028 has been restored! Reason: EXPIRED```
```
Possible error when region expires. It restores the region as intended but maybe a submethod isn't currently working within it.

**Comment by alex9849** [comment]
Thats not from AdvancedRegionMarket but from the ShopBridge. To be more precisely the error comes from the Quickshop integration. The newer Quickshop versions support ARM natively and don't need the shopbridge. The problem can be solved if you just remove the plugin. :)
