### ISSUE TITLE
[Bug] UnsupportedVersionEditException

### ISSUE THREAD

**Issue by Baktus79** [alex9849/advanced-region-market#95]
**Description**
The error message below appears in the console and constantly spamming.

---

```
[08:01:52] [Server thread/WARN]: [AdvancedRegionMarket] Task #71 for AdvancedRegionMarket v3.3.7 generated an exception
java.lang.RuntimeException: com.sk89q.worldedit.bukkit.adapter.UnsupportedVersionEditException: Editing on unsupported versions is disabled.
	at com.sk89q.worldedit.bukkit.BukkitWorld.getBlock(BukkitWorld.java:457) ~[worldedit-bukkit-7.2.8.jar:?]
	at com.sk89q.worldedit.bukkit.BukkitWorld.getFullBlock(BukkitWorld.java:491) ~[worldedit-bukkit-7.2.8.jar:?]
	at org.primesoft.asyncworldedit.worldedit.world.AsyncWorld.lambda$getFullBlockDispatcher$19(AsyncWorld.java:791) ~[?:?]
	at org.primesoft.asyncworldedit.taskdispatcher.TaskDispatcher.performSafe(TaskDispatcher.java:643) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.world.AsyncWorld.getFullBlockDispatcher(AsyncWorld.java:790) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.world.AsyncWorld.lambda$getBlockEntry$21(AsyncWorld.java:808) ~[?:?]
	at java.util.HashMap.computeIfAbsent(HashMap.java:1220) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.world.AsyncWorld.getBlockEntry(AsyncWorld.java:807) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.world.AsyncWorld.getFullBlock(AsyncWorld.java:830) ~[?:?]
	at com.sk89q.worldedit.EditSession.getFullBlock(EditSession.java:686) ~[worldedit-bukkit-7.2.8.jar:?]
	at org.primesoft.asyncworldedit.worldedit.ThreadSafeEditSession.doGetFullBlock(ThreadSafeEditSession.java:815) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.ThreadSafeEditSession.lambda$getFullBlock$2(ThreadSafeEditSession.java:554) ~[?:?]
	at org.primesoft.asyncworldedit.taskdispatcher.TaskDispatcher.performSafe(TaskDispatcher.java:643) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.ThreadSafeEditSession.getFullBlock(ThreadSafeEditSession.java:554) ~[?:?]
	at com.sk89q.worldedit.function.block.ExtentBlockCopy.apply(ExtentBlockCopy.java:72) ~[worldedit-bukkit-7.2.8.jar:?]
	at com.sk89q.worldedit.function.RegionMaskingFilter.apply(RegionMaskingFilter.java:53) ~[worldedit-bukkit-7.2.8.jar:?]
	at com.sk89q.worldedit.function.visitor.RegionVisitor.resume(RegionVisitor.java:60) ~[worldedit-bukkit-7.2.8.jar:?]
	at com.sk89q.worldedit.function.operation.OperationQueue.resume(OperationQueue.java:92) ~[worldedit-bukkit-7.2.8.jar:?]
	at com.sk89q.worldedit.function.operation.DelegateOperation.resume(DelegateOperation.java:52) ~[worldedit-bukkit-7.2.8.jar:?]
	at com.sk89q.worldedit.function.operation.Operations.__2d0b6d9ce5f34215a57399c20239ce28__completeLegacy(Operations.java:55) ~[worldedit-bukkit-7.2.8.jar:?]
	at com.sk89q.worldedit.function.operation.Operations_InnerForMethod__2d0b6d9ce5f34215a57399c20239ce28__completeLegacy.execute(Unknown Source) ~[worldedit-bukkit-7.2.8.jar:?]
	at org.primesoft.asyncworldedit.asyncinjector.async.AsyncOperationProcessor.process(AsyncOperationProcessor.java:125) ~[?:?]
	at org.primesoft.asyncworldedit.injector.core.visitors.Helpers.executeMethodEx(Helpers.java:99) ~[AsyncWorldEdit-3.9.4.jar:?]
	at com.sk89q.worldedit.function.operation.Operations.completeLegacy(Operations.java) ~[worldedit-bukkit-7.2.8.jar:?]
	at net.alex9849.adapters.WorldEdit7.createSchematic(WorldEdit7.java:59) ~[advancedregionmarket-3.3.7.jar:?]
	at net.alex9849.arm.regions.Region.createBackup(Region.java:912) ~[advancedregionmarket-3.3.7.jar:?]
	at net.alex9849.arm.regions.Region.unsell(Region.java:1106) ~[advancedregionmarket-3.3.7.jar:?]
	at net.alex9849.arm.regions.CountdownRegion.unsell(CountdownRegion.java:67) ~[advancedregionmarket-3.3.7.jar:?]
	at net.alex9849.arm.regions.Region.automaticResetRegion(Region.java:1075) ~[advancedregionmarket-3.3.7.jar:?]
	at net.alex9849.arm.regions.RentRegion.updateRegion(RentRegion.java:148) ~[advancedregionmarket-3.3.7.jar:?]
	at net.alex9849.arm.regions.RegionManager$UpdateScheduler.updateNextGroup(RegionManager.java:972) ~[advancedregionmarket-3.3.7.jar:?]
	at net.alex9849.arm.regions.RegionManager.doTick(RegionManager.java:876) ~[advancedregionmarket-3.3.7.jar:?]
	at net.alex9849.arm.AdvancedRegionMarket.lambda$startup$0(AdvancedRegionMarket.java:223) ~[advancedregionmarket-3.3.7.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-231]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.2.jar:git-Paper-231]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1535) ~[paper-1.18.2.jar:git-Paper-231]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-231]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1458) ~[paper-1.18.2.jar:git-Paper-231]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1227) ~[paper-1.18.2.jar:git-Paper-231]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.2.jar:git-Paper-231]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: com.sk89q.worldedit.bukkit.adapter.UnsupportedVersionEditException: Editing on unsupported versions is disabled.
	... 41 more
```

---

**Server:** Paper 1.18.2 Build 231
**Worldedit Version:** 7.2.8
**ARM Version:** 3.3.7

*Also testet with Worldedit v7.2.9.*

**Comment by alex9849** [comment]
WorldEdit doesn't support the 1.18.2 build yet. The last stable release is for 1.18.1.
You can also get that information from this message in the error:
`Editing on unsupported versions is disabled.`

The only thing you can do is waiting for a stable WorldEdit build that supports the 1.18.2 version.
I mean you should wait for a stable version. But you could also use an experimental build. For example this one here:
https://builds.enginehub.org/job/worldedit/19838

But keep in mind that this isn't recommended and using experimental build could cause serious harm to your server if you are unlucky.
